Repository rapidsai/docker, pull requests merged in 2020-02, with the labels that each got.

#51 Adding cuxfilter and doc updates
  README.md
  doc/NGC_rapidsai.md
  repoSettings
  templates/docker/build_rapids
Labels: 3 - Ready for Review

#53 [ENH] Adding cuxfilter to runtime images
  generatedDockerfiles/Dockerfile.centos7-base
  generatedDockerfiles/Dockerfile.centos7-devel
  generatedDockerfiles/Dockerfile.centos7-runtime
  generatedDockerfiles/Dockerfile.ubuntu-base
  generatedDockerfiles/Dockerfile.ubuntu-devel
  generatedDockerfiles/Dockerfile.ubuntu-runtime
  templates/docker/conda_install_notebookenv
Labels: containers

#54 Note cuxfilter is only in runtime containers
  doc/Dockerhub_rapidsai-dev-nightly.md
  doc/Dockerhub_rapidsai-dev.md
  doc/Dockerhub_rapidsai-nightly.md
  doc/Dockerhub_rapidsai.md
  doc/NGC_rapidsai.md
Labels: 3 - Ready for Review

#55 [RELEASE] build v0.12
  doc/Dockerhub_rapidsai-dev-nightly.md
  doc/Dockerhub_rapidsai-dev.md
  doc/Dockerhub_rapidsai-nightly.md
  doc/Dockerhub_rapidsai.md
  doc/NGC_rapidsai.md
  generatedDockerfiles/Dockerfile.centos7-base
  generatedDockerfiles/Dockerfile.centos7-devel
  generatedDockerfiles/Dockerfile.centos7-runtime
  generatedDockerfiles/Dockerfile.ubuntu-base
  generatedDockerfiles/Dockerfile.ubuntu-devel
  generatedDockerfiles/Dockerfile.ubuntu-runtime
  templates/docker/conda_install_notebookenv
Labels: ! - Release

#56 Use new conda rapids env meta-pkgs
  dockerArgs
  templates/docker/Dockerfile_centos7-devel.template
  templates/docker/Dockerfile_ubuntu-devel.template
  templates/docker/conda_install_devel_deps
  templates/docker/conda_install_notebookenv
Labels: 3 - Ready for Review

#57 Add Quick Devel Build
  templates/docker/Dockerfile_centos7-quick.template
  templates/docker/Dockerfile_ubuntu-devel.template
  templates/docker/Dockerfile_ubuntu-quick.template
  templates/docker/update_rapids
Labels: 3 - Ready for Review
