Repository rapidsai/docker, pull requests merged in 2020-03, with the labels that each got.

#66 Fix gcc 7 update issues
  templates/docker/gcc7_centos7
  templates/docker/gcc7_ubuntu
Labels: 3 - Ready for Review, bug

#69 DOC Add some clarification to the README
  README.md
Labels: 3 - Ready for Review, doc

#68 Organize readme into separate files
  README.md
  add-repo.md
  common-build-problems.md
  tooling.md
Labels: 5 - Ready to Merge, doc
