Repository rapidsai/docker, pull requests merged in 2025-02, with the labels that each got.

#727 avoid interactive prompts when updating from an environment.yaml
  context/entrypoint.sh
  context/test_notebooks.py
Labels: bug

#735 Set NCCL_CUMEM_HOST_ENABLE=0 for ARM with CUDA 12.8
  context/entrypoint.sh
Labels: bug, non-breaking

#729 Migrate to NVKS for amd64 CI runners
  matrix-test.yaml
Labels: improvement, non-breaking
